### ISSUE TITLE
Add `.log` file

### ISSUE THREAD

**Issue by wak3upalex** [wak3upalex/eestecbot#25]
# DESCRIPTION
Currently logs are made in some parts of code. 
Moreover, logs are being pushed in console

# TODO
- [x] Add logs for every part of code
- [x] Save logs in the `.log` file
- [x] Check out the style of log messages 

# IMPORTANT NOTICE
**DO NOT FORGET TO**
**1. UPDATE YOUR PROJECT LOCALLY**
**2. CREATE A BRACH FOR THIS FEATURE**
**3. ALWAYS UPDATE STATUS OF WORKING ON THIS ISSUE IN OUR PROJECT TRACKER**
**4. MAKE A PULL REQUEST AND ASK FOR A REVIEW OF @wak3upalex**

**Comment by wak3upalex** [comment]
Closed in 9492cb4bcfc52fdd75a6d39650c136cb7cc3d67a
