### ISSUE TITLE
Add text of questions and answers for `/quest`

### ISSUE THREAD

**Issue by wak3upalex** [wak3upalex/eestecbot#26]
This issue should be solved in the same PR as issue #27
Do all the work for both of these branches on branch
`fix-quest-questions-result`

# DESCRIPTION
@NikitaZavorin you will get a message from @wak3upalex with text  for questions and answers

# TODO
- [ ] add text for questions
- [ ] Add text for answers 
- [ ] Check that answers are in correct positions for each team
## IMPORTANT NOTICE
**DO NOT FORGET TO**
**1. UPDATE YOUR PROJECT LOCALLY**
**2. CREATE A BRACH FOR THIS FEATURE**
**3. ALWAYS UPDATE STATUS OF WORKING ON THIS ISSUE IN OUR PROJECT TRACKER**
**4. MAKE A PULL REQUEST AND ASK FOR A REVIEW OF @wak3upalex**
