### ISSUE TITLE
Add a result message with better description of each team

### ISSUE THREAD

**Issue by wak3upalex** [wak3upalex/eestecbot#27]
This issue should be solved in the same PR as issue #26
Do all the work for both of these branches on branch
`fix-quest-questions-result`

# DESCRIPTION 
Currently after passing the test user gets message which team OR teams are recommended for him or her. 

IN ADDITION TO THIS, send a user message with description of the team(which was recommended in a result of the test/quest). If several teams recommended for a user, bot will send 1 separate description message for each recommended team after test. 

## IMPORTANT NOTICE

# TODO
- [ ] add text for questions
- [ ] Add text for answers 
- [ ] Check that answers are in correct positions for each team

## IMPORTANT NOTICE
**DO NOT FORGET TO**
**1. UPDATE YOUR PROJECT LOCALLY**
**2. CREATE A BRACH FOR THIS FEATURE**
**3. ALWAYS UPDATE STATUS OF WORKING ON THIS ISSUE IN OUR PROJECT TRACKER**
**4. MAKE A PULL REQUEST AND ASK FOR A REVIEW OF @wak3upalex**
